server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
