import { expect, test, type Page } from '@playwright/test'

// Isolated UI regression checks. Every API request is intercepted; no accounts,
// orders, payments, or seller records are created in the running backend.
const listing = { id: 'qa-product', slug: 'qa-studio-headphones', sellerId: 'qa-seller', title: 'Studio Headphones QA', brand: 'Studio QA', categorySlug: 'audio', priceInPaise: 1299900, originalPriceInPaise: 1599900, description: 'Wireless headphones for everyday listening.', images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80'], tags: ['audio', 'wireless'], badge: 'New arrival', delivery: 'Free delivery in 2 days', rating: 4.8, reviewCount: 128, active: true }
const address = { fullName: 'Design Tester', phone: '9999999999', postalCode: '751001', line1: '1 Test Avenue', line2: '', city: 'Bhubaneswar', state: 'Odisha' }
const order = { id: 'qa-order', orderNumber: 'NC-QA-001', userId: 'qa-seller', shippingAddressJson: JSON.stringify(address), items: [{ productId: listing.slug, productName: listing.title, productImage: listing.images[0], sellerId: 'qa-seller', unitPricePaise: listing.priceInPaise, quantity: 1, subtotalPaise: listing.priceInPaise, fulfillmentStatus: 'PROCESSING' }], subtotalPaise: listing.priceInPaise, shippingFeePaise: 0, discountPaise: 0, taxPaise: 0, totalPaise: listing.priceInPaise, currency: 'INR', status: 'CONFIRMED', sagaState: 'ORDER_CONFIRMED', idempotencyKey: 'qa-only', createdAt: '2026-09-16T12:00:00Z' }

async function fixtures(page: Page, { seller = false, guest = false, bag = false } = {}) {
  const errors: string[] = []
  const writes: Array<{path: string; method: string; body: Record<string, unknown>}> = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.addInitScript(({bag, slug}) => {
    if (!localStorage.getItem('novacart-theme')) localStorage.setItem('novacart-theme', 'light')
    if (!localStorage.getItem('novacart-commerce')) localStorage.setItem('novacart-commerce', JSON.stringify({state:{cart:bag ? {[slug]:1} : {}, wishlist:[], syncedUserId:'qa-seller'},version:0}))
  }, {bag,slug:listing.slug})
  await page.route('**/api/v1/**', async (route) => {
    const request = route.request()
    const path = new URL(request.url()).pathname.replace('/api/v1','')
    const method = request.method()
    if (method !== 'GET' && method !== 'OPTIONS') writes.push({path,method,body: request.postDataJSON() ?? {}})
    const send = (body: unknown, status = 200) => route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)})
    if (method === 'OPTIONS') return route.fulfill({status:204})
    if (path === '/auth/refresh') return guest ? send({success:false},401) : send({success:true,data:{accessToken:'ui-test-token',user:{id:'qa-seller',fullName:'Design Tester',email:'design@example.test',roles:[seller ? 'ROLE_SELLER' : 'ROLE_CUSTOMER']}}})
    if (path === '/products/seller/me') return send([listing])
    if (path === '/products' && method === 'GET') return send({content:[listing],totalElements:1,totalPages:1,number:0,size:100})
    if (path.startsWith('/products/') && path.endsWith('/reviews')) return send([])
    if (path.startsWith('/products')) return send(listing)
    if (path === '/inventory/availability') return send({[listing.slug]:25})
    if (path === '/inventory/seller/me') return send([{productId:listing.slug,availableQuantity:25,reservedQuantity:0,lowStockThreshold:5}])
    if (path.startsWith('/inventory')) return send({productId:listing.slug,availableQuantity:25,reservedQuantity:0,lowStockThreshold:5})
    if (path === '/cart') return send({items:[],itemCount:0})
    if (path.startsWith('/cart')) return send({})
    if (path.startsWith('/wishlist')) return send({productIds:[]})
    if (path === '/payments/coupons/apply') return send({code:'NOVA10',discountPaise:129990,finalAmountPaise:1169910})
    if (path === '/payments/config') return send({keyId:'mock',live:false})
    if (path.startsWith('/payments/order/')) return send({id:'qa-payment',orderId:'qa-order',razorpayOrderId:'qa-rzp-order',amountPaise:listing.priceInPaise,currency:'INR',status:'CREATED'})
    if (path === '/orders' && method === 'POST') return send({...order,...request.postDataJSON(),status:'AWAITING_PAYMENT',sagaState:'STOCK_RESERVED'})
    if (path === '/orders' || path.startsWith('/orders/seller')) return send({content:[order],totalElements:1,totalPages:1,number:0})
    if (path.startsWith('/orders/')) return send(order)
    return send({})
  })
  return {errors,writes}
}

async function fits(page: Page) {
  const width = await page.evaluate(() => ({body:document.documentElement.scrollWidth,view:window.innerWidth}))
  expect(width.body).toBeLessThanOrEqual(width.view + 1)
}

async function preparePhotos(page: Page) {
  // Let actual artwork load before visual review, including lazy-loaded photos.
  await page.locator('img').evaluateAll((images) => images.forEach((image) => { image.loading = 'eager' }))
  await expect.poll(() => page.locator('.nc-feature-main img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0), {timeout:25000}).toBe(true)
  await page.evaluate(async () => { await document.fonts.ready })
}

async function capture(page: Page, path: string) {
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}))
  await page.screenshot({path,fullPage:true})
}

test('desktop storefront, theme persistence, filters, live product cart, and keyboard dialogs', async ({page}, testInfo) => {
  const {errors} = await fixtures(page)
  await page.setViewportSize({width:1440,height:1000})
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Find your next favourite.'})).toBeVisible()
  await preparePhotos(page)
  await page.screenshot({path:testInfo.outputPath('home-light-viewport.png')})
  await capture(page,testInfo.outputPath('home-light.png'))
  await page.getByRole('button',{name:'Switch to dark mode'}).click()
  await expect(page.locator('html')).toHaveClass('dark')
  await capture(page,testInfo.outputPath('home-dark.png'))
  await page.reload()
  await expect(page.locator('html')).toHaveClass('dark')
  await page.getByLabel('Filter by brand').selectOption('Studio QA')
  await expect(page.locator('.nc-product-card')).toHaveCount(1)
  await page.getByLabel('Sort products').selectOption('price-low')
  await page.getByRole('button',{name:`Add ${listing.title} to cart`,exact:true}).click()
  await page.getByRole('button',{name:'Open cart with 1 items'}).click()
  const dialog = page.getByRole('dialog',{name:/Your bag/})
  await expect(dialog.getByRole('heading',{name:listing.title})).toBeVisible()
  await dialog.getByRole('button',{name:`Increase ${listing.title} quantity`}).click()
  await expect(page.getByRole('button',{name:'Open cart with 2 items'})).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('button',{name:'Open cart with 2 items'})).toBeFocused()
  await page.getByRole('button',{name:`Quick view ${listing.title}`}).click()
  await expect(page.getByRole('dialog',{name:listing.title})).toBeVisible()
  await page.keyboard.press('Shift+Tab')
  expect(await page.getByRole('dialog',{name:listing.title}).evaluate((dialog) => dialog.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog',{name:'Explore categories'})).toBeVisible()
  await page.getByRole('textbox',{name:'Search NovaCart'}).fill('headphones')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/search\?q=headphones/)
  await fits(page)
  expect(errors).toEqual([])
})

test('hero Nova AI action opens the existing assistant on desktop and mobile', async ({page}, testInfo) => {
  const {errors} = await fixtures(page)
  for (const width of [1440,390]) {
    await page.setViewportSize({width,height:900})
    await page.goto('/')
    const hero = page.getByRole('region',{name:'Find your next favourite.'})
    await expect(hero.getByRole('link',{name:'Explore the collection'})).toBeVisible()
    await expect(hero.getByRole('link',{name:'Just landed'})).toBeVisible()
    await hero.getByRole('button',{name:'Ask Nova AI'}).click()
    await expect(hero.getByRole('button',{name:'Ask Nova AI'})).toHaveAttribute('aria-expanded','true')
    await expect(page.getByRole('textbox',{name:'Ask Nova AI'})).toBeVisible()
    await expect(page.getByRole('textbox',{name:'Ask Nova AI'})).toBeFocused()
    await fits(page)
    await page.getByRole('button',{name:'Collapse AI Panel'}).click()
    await expect(hero.getByRole('button',{name:'Ask Nova AI'})).toHaveAttribute('aria-expanded','false')
    await page.getByRole('button',{name:'Switch to dark mode',exact:true}).click()
    await capture(page,testInfo.outputPath(`nova-hero-${width}.png`))
    await hero.getByRole('button',{name:'Ask Nova AI'}).click()
    await expect(page.getByRole('textbox',{name:'Ask Nova AI'})).toBeVisible()
    await fits(page)
    await page.getByRole('button',{name:'Switch to light mode',exact:true}).click()
  }
  expect(errors).toEqual([])
})

test('product purchase, wishlist and removing items keep the shared counts in sync', async ({page}) => {
  const {errors} = await fixtures(page)
  await page.goto(`/products/${listing.slug}`)
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByRole('link',{name:'Wishlist with 1 items'})).toBeVisible()
  await page.getByRole('button',{name:'Buy now',exact:true}).click()
  await expect(page).toHaveURL(/checkout$/)
  await expect(page.getByRole('button',{name:'Open cart with 1 items'})).toBeVisible()
  await page.getByRole('button',{name:'Open cart with 1 items'}).click()
  await page.getByRole('button',{name:`Remove ${listing.title}`,exact:true}).click()
  await expect(page.getByRole('button',{name:'Open cart with 0 items'})).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('link',{name:'Wishlist with 1 items'}).click()
  await expect(page.locator('.nc-product-card')).toHaveCount(1)
  await page.getByRole('button',{name:`Remove ${listing.title} from wishlist`}).click()
  await expect(page.locator('.nc-product-card')).toHaveCount(0)
  await expect(page.getByRole('link',{name:'Wishlist with 0 items'})).toBeVisible()
  expect(errors).toEqual([])
})

test('small phones, tablets and compact desktops have no horizontal page overflow', async ({page}) => {
  const {errors} = await fixtures(page,{seller:true,bag:true})
  for (const width of [320,768,1024]) {
    await page.setViewportSize({width,height:900})
    for (const path of ['/','/checkout','/seller',`/products/${listing.slug}`]) {
      await page.goto(path)
      await expect(page.locator('h1').first()).toBeVisible()
      await fits(page)
    }
  }
  expect(errors).toEqual([])
})

test('mobile navigation, forms and dialogs fit a narrow screen', async ({page},testInfo) => {
  const {errors} = await fixtures(page,{bag:true})
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Find your next favourite.'})).toBeVisible()
  await preparePhotos(page)
  await fits(page)
  await capture(page,testInfo.outputPath('mobile-home.png'))
  await page.getByRole('button',{name:'Toggle navigation'}).click()
  await expect(page.getByRole('navigation',{name:'Mobile navigation'})).toBeVisible()
  await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('link',{name:'My profile'}).click()
  await expect(page).toHaveURL(/profile$/)
  await fits(page)
  await page.goto('/cart')
  await expect(page.getByRole('heading',{name:'Your good finds.'})).toBeVisible()
  await fits(page)
  await capture(page,testInfo.outputPath('mobile-cart.png'))
  await page.goto('/checkout')
  await page.getByRole('button',{name:'Continue to payment'}).click()
  await expect(page.getByText('Enter the recipient’s full name')).toBeVisible()
  await fits(page)
  await capture(page,testInfo.outputPath('mobile-checkout.png'))
  expect(errors).toEqual([])
})

test('checkout preserves seller identity, coupons and delivery validation', async ({page},testInfo) => {
  const {writes,errors} = await fixtures(page,{bag:true})
  await page.setViewportSize({width:1440,height:1000})
  await page.goto('/checkout')
  await page.getByLabel('Full name').fill(address.fullName)
  await page.getByLabel('Mobile number').fill(address.phone)
  await page.getByLabel('PIN code').fill(address.postalCode)
  await page.getByLabel('Address',{exact:true}).fill(address.line1)
  await page.getByLabel('City',{exact:true}).fill(address.city)
  await page.getByLabel('State',{exact:true}).fill(address.state)
  await page.getByLabel('Coupon code').fill('NOVA10')
  await page.getByRole('button',{name:'Apply',exact:true}).click()
  await expect(page.getByRole('button',{name:'Remove coupon'})).toBeVisible()
  await capture(page,testInfo.outputPath('checkout-light.png'))
  await page.getByRole('button',{name:'Continue to payment'}).click()
  await expect(page).toHaveURL(/payment$/)
  const payload = writes.find((request) => request.path === '/orders')!.body
  expect(payload.couponCode).toBe('NOVA10')
  expect(payload.items).toEqual(expect.arrayContaining([expect.objectContaining({sellerId:'qa-seller',productId:listing.slug,quantity:1})]))
  await expect(page.getByRole('button',{name:/Pay securely/})).toBeEnabled()
  await capture(page,testInfo.outputPath('payment-light.png'))
  expect(errors).toEqual([])
})

test('seller overview, searchable inventory, editor, orders and fulfillment', async ({page},testInfo) => {
  const {writes,errors} = await fixtures(page,{seller:true})
  await page.setViewportSize({width:1440,height:1000})
  await page.goto('/seller')
  await expect(page.getByRole('heading',{name:'Good to see you, Design.'})).toBeVisible()
  await expect(page.getByRole('heading',{name:listing.title})).toBeVisible()
  await capture(page,testInfo.outputPath('seller-light.png'))
  await page.getByRole('button',{name:'Switch to dark mode'}).click()
  await capture(page,testInfo.outputPath('seller-dark.png'))
  await page.getByRole('button',{name:'Products & inventory',exact:true}).click()
  await page.getByLabel('Search your products').fill('nothing-matches')
  await expect(page.getByText('No products match your search.')).toBeVisible()
  await page.getByLabel('Search your products').fill('Studio')
  await page.getByRole('button',{name:`Edit ${listing.title}`}).click()
  const editor = page.getByRole('dialog',{name:'Refine your product.'})
  await expect(editor.getByLabel('Product title')).toHaveValue(listing.title)
  await editor.getByLabel('Product title').fill('Edited headphones')
  await editor.getByRole('button',{name:'Save changes'}).click()
  await expect(editor).not.toBeVisible()
  expect(writes.some((request) => request.path === '/products/qa-product' && request.body.title === 'Edited headphones')).toBe(true)
  await page.getByRole('button',{name:'Orders',exact:true}).click()
  await page.getByRole('button',{name:/NC-QA-001/}).click()
  await page.getByRole('button',{name:'Mark as shipped'}).click()
  expect(writes.some((request) => request.path.includes('fulfillment'))).toBe(true)
  await page.setViewportSize({width:390,height:844})
  await fits(page)
  await page.getByRole('button',{name:'Add product',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await fits(page)
  await page.keyboard.press('Escape')
  expect(errors).toEqual([])
})

test('auth pages, account pages and product details retain usable light and dark layouts', async ({page},testInfo) => {
  const {errors} = await fixtures(page)
  await page.setViewportSize({width:1440,height:1000})
  await page.goto(`/products/${listing.slug}`)
  await expect(page.getByRole('heading',{name:listing.title,exact:true})).toBeVisible()
  await fits(page)
  await capture(page,testInfo.outputPath('product-light.png'))
  for (const path of ['/orders','/orders/qa-order','/profile','/settings','/wishlist','/categories']) {
    await page.goto(path)
    await expect(page.locator('h1').first()).toBeVisible()
    await fits(page)
    await page.getByRole('button',{name:'Switch to dark mode',exact:true}).click()
    await fits(page)
    await page.getByRole('button',{name:'Switch to light mode',exact:true}).click()
  }
  await page.goto('/login')
  await expect(page.getByRole('textbox',{name:'Email'})).toBeVisible()
  await capture(page,testInfo.outputPath('login-light.png'))
  await page.setViewportSize({width:390,height:844})
  await fits(page)
  expect(errors).toEqual([])
})
