import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, CalendarDays, Download, MapPin, PackageSearch, ReceiptText, RefreshCw, RotateCcw } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { cancelOrder, getOrder } from '../api/orders'
import { getPayment } from '../api/payments'
import { OrderTrackingTimeline } from '../components/OrderTrackingTimeline'
import type { DeliveryAddress } from '../stores/checkout-store'
import type { Order } from '../types/saga'

const money = (paise: number) => `₹${(paise / 100).toLocaleString('en-IN')}`
const dateTime = (value: string) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'long', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value))

export function OrderTrackingPage() {
  const { id } = useParams()
  const queryClient = useQueryClient()
  const query = useQuery({ queryKey: ['order', id], queryFn: () => getOrder(id!), enabled: Boolean(id), refetchInterval: (state) => ['PENDING', 'AWAITING_PAYMENT', 'SHIPPED'].includes(state.state.data?.status ?? '') ? 4000 : false })
  const payment = useQuery({ queryKey: ['payment', id], queryFn: () => getPayment(id!), enabled: Boolean(id && query.data && !['PENDING', 'AWAITING_PAYMENT'].includes(query.data.status)), retry: false, refetchInterval: query.data?.status === 'CANCELLED' ? 4000 : false })
  const cancel = useMutation({ mutationFn: () => cancelOrder(id!), onSuccess: (order) => { queryClient.setQueryData(['order', id], order); void queryClient.invalidateQueries({ queryKey: ['orders'] }); void queryClient.invalidateQueries({ queryKey: ['payment', id] }) } })

  if (query.isLoading) return <main className="min-h-[70vh] bg-[var(--nc-bg)] px-5 py-14"><div className="mx-auto max-w-5xl"><div className="h-8 w-40 animate-pulse rounded-full bg-black/[.05] dark:bg-white/[.05]" /><div className="mt-8 h-96 animate-pulse rounded-[2rem] bg-black/[.04] dark:bg-white/[.04]" /></div></main>
  if (!id || query.isError || !query.data) return <main className="flex min-h-[70vh] items-center bg-[var(--nc-bg)] px-5 py-16 text-center text-[var(--nc-text)]"><div className="mx-auto max-w-lg"><div className="mx-auto grid h-20 w-20 place-items-center rounded-[1.6rem] bg-slate-950 text-white"><PackageSearch className="h-8 w-8 text-[#dfff36]" /></div><p className="nc-label mt-7">Order unavailable</p><h1 className="mt-4 text-h2">We couldn’t find this order.</h1><p className="mt-5 text-sm leading-7 text-slate-500">It may not belong to this account, or the Order Service is temporarily unavailable.</p><div className="mt-8 flex justify-center gap-3"><Link to="/orders" className="nc-secondary"><ArrowLeft className="h-4 w-4" /> Back to orders</Link><button onClick={() => query.refetch()} className="nc-primary"><RefreshCw className="h-4 w-4" /> Retry</button></div></div></main>

  const order = query.data
  let address: DeliveryAddress | null = null
  try { address = JSON.parse(order.shippingAddressJson) as DeliveryAddress } catch { address = null }
  const canCancel = ['PENDING', 'AWAITING_PAYMENT', 'CONFIRMED'].includes(order.status)
  const paid = payment.data && ['CAPTURED', 'REFUNDED'].includes(payment.data.status)
  const refundPending = order.status === 'CANCELLED' && payment.data?.status === 'CAPTURED'
  const refunded = payment.data?.status === 'REFUNDED'

  return <><main className="min-h-[70vh] bg-[var(--nc-bg)] px-5 py-12 text-[var(--nc-text)] sm:px-8 lg:py-16"><div className="mx-auto max-w-5xl">
    <Link to="/orders" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-violet-600 dark:hover:text-[#dfff36]"><ArrowLeft className="h-4 w-4" /> All orders</Link>
    <header className="mt-7 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="nc-label">Live order tracking</p><h1 className="mt-3 text-h2">{order.orderNumber}</h1><p className="mt-3 flex items-center gap-2 text-xs text-slate-500"><CalendarDays className="h-4 w-4" /> Placed {dateTime(order.createdAt)}</p></div><div className="text-left sm:text-right"><p className="text-xs text-slate-500">Order total</p><p className="mt-1 text-3xl font-black tracking-[-.04em]">{money(order.totalPaise)}</p>{paid && <button onClick={() => window.print()} className="mt-3 inline-flex items-center gap-2 text-xs font-black text-violet-600 dark:text-[#dfff36]"><Download className="h-4 w-4" /> Download invoice</button>}</div></header>
    <section className="mt-8 rounded-[2rem] border border-black/10 bg-[var(--nc-surface)] p-6 shadow-card dark:border-white/10 sm:p-8"><OrderTrackingTimeline sagaState={order.sagaState} status={order.status} /></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_340px]">
      <section className="rounded-[2rem] border border-black/10 bg-[var(--nc-surface)] p-5 dark:border-white/10 sm:p-7"><div className="flex items-center justify-between"><div><p className="nc-label">Inside your order</p><h2 className="mt-2 text-xl font-black">{order.items.reduce((sum, item) => sum + item.quantity, 0)} items</h2></div><ReceiptText className="h-5 w-5 text-violet-600 dark:text-[#dfff36]" /></div><div className="mt-6 divide-y divide-black/10 dark:divide-white/10">{order.items.map((item) => <article key={item.id ?? item.productId} className="flex gap-4 py-4 first:pt-0 last:pb-0"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-2xl bg-[var(--nc-surface-raised)]"><img src={item.productImage || '/favicon.svg'} alt={item.productName} className="h-full w-full object-cover" /></div><div className="min-w-0 flex-1"><p className="text-sm font-black">{item.productName}</p><p className="mt-2 text-xs text-slate-500">Quantity {item.quantity}</p><p className="mt-2 text-sm font-bold">{money(item.subtotalPaise)}</p>{item.fulfillmentStatus && <p className="mt-2 text-[10px] font-black uppercase tracking-wide text-violet-600 dark:text-[#dfff36]">{item.fulfillmentStatus.replace('_', ' ')}</p>}</div></article>)}</div></section>
      <aside className="space-y-5"><AddressCard address={address} />{(refundPending || refunded) && <section className={`rounded-[1.5rem] border p-5 ${refunded ? 'border-emerald-300/40 bg-emerald-50 dark:border-emerald-400/20 dark:bg-emerald-400/[.07]' : 'border-amber-300/50 bg-amber-50 dark:border-amber-400/20 dark:bg-amber-400/[.07]'}`}><RotateCcw className={`h-5 w-5 ${refunded ? 'text-emerald-600' : 'text-amber-600'}`} /><p className="mt-3 text-sm font-black">{refunded ? 'Refund completed' : 'Refund processing'}</p><p className="mt-2 text-xs leading-5 text-slate-500">{refunded ? `${money(payment.data!.amountPaise)} has been returned to your original payment method.` : 'Your cancellation is confirmed. The payment service is processing your refund.'}</p></section>}{canCancel && <section className="rounded-[1.5rem] border border-black/10 bg-[var(--nc-surface)] p-5 dark:border-white/10"><p className="text-sm font-black">Changed your mind?</p><p className="mt-2 text-xs leading-5 text-slate-500">You can cancel before dispatch. Reserved stock is released automatically and captured payments are refunded.</p><button onClick={() => cancel.mutate()} disabled={cancel.isPending} className="mt-4 text-xs font-black text-rose-600 disabled:opacity-50">{cancel.isPending ? 'Cancelling…' : 'Cancel order'}</button>{cancel.isError && <p className="mt-2 text-xs text-rose-500">Cancellation could not be completed.</p>}</section>}</aside>
    </div>
  </div></main>{paid && <Invoice order={order} address={address} paymentId={payment.data?.razorpayPaymentId ?? payment.data?.id ?? ''} />}</>
}

function AddressCard({ address }: { address: DeliveryAddress | null }) {
  return <section className="rounded-[2rem] bg-slate-950 p-6 text-white"><p className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-[#dfff36]"><MapPin className="h-4 w-4" /> Delivery address</p>{address ? <div className="mt-5 text-sm"><p className="font-black">{address.fullName}</p><p className="mt-2 leading-6 text-slate-400">{address.line1}{address.line2 ? `, ${address.line2}` : ''}<br />{address.city}, {address.state} — {address.postalCode}<br />+91 {address.phone}</p></div> : <p className="mt-4 text-xs text-slate-400">Address details are securely stored with this order.</p>}</section>
}

function Invoice({ order, address, paymentId }: { order: Order; address: DeliveryAddress | null; paymentId: string }) {
  return <section className="nc-print-invoice hidden bg-white p-10 text-slate-950"><div className="flex items-start justify-between border-b-2 border-slate-950 pb-7"><div><p className="text-3xl font-black">NovaCart</p><p className="mt-1 text-xs uppercase tracking-[.22em]">Smart shopping. Better living.</p></div><div className="text-right"><h1 className="text-2xl font-black">TAX INVOICE</h1><p className="mt-2 text-sm">{order.orderNumber}</p></div></div><div className="mt-8 grid grid-cols-2 gap-10 text-sm"><div><p className="font-black uppercase">Billed and delivered to</p><p className="mt-3 leading-6">{address ? <>{address.fullName}<br />{address.line1}{address.line2 ? `, ${address.line2}` : ''}<br />{address.city}, {address.state} — {address.postalCode}<br />+91 {address.phone}</> : 'Address stored with order'}</p></div><div className="text-right"><p><strong>Invoice date:</strong> {dateTime(order.createdAt)}</p><p className="mt-2"><strong>Payment reference:</strong> {paymentId}</p><p className="mt-2"><strong>Currency:</strong> {order.currency}</p></div></div><table className="mt-10 w-full border-collapse text-sm"><thead><tr className="border-y-2 border-slate-950 text-left"><th className="py-3">Item</th><th className="py-3 text-center">Qty</th><th className="py-3 text-right">Unit price</th><th className="py-3 text-right">Amount</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id ?? item.productId} className="border-b border-slate-300"><td className="py-4 pr-4 font-bold">{item.productName}</td><td className="py-4 text-center">{item.quantity}</td><td className="py-4 text-right">{money(item.unitPricePaise)}</td><td className="py-4 text-right">{money(item.subtotalPaise)}</td></tr>)}</tbody></table><div className="ml-auto mt-7 w-72 space-y-3 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(order.subtotalPaise)}</span></div>{order.discountPaise > 0 && <div className="flex justify-between"><span>Discount</span><span>−{money(order.discountPaise)}</span></div>}<div className="flex justify-between"><span>Delivery</span><span>{order.shippingFeePaise ? money(order.shippingFeePaise) : 'Free'}</span></div><div className="flex justify-between border-t-2 border-slate-950 pt-3 text-lg font-black"><span>Total</span><span>{money(order.totalPaise)}</span></div></div><p className="mt-16 border-t border-slate-300 pt-5 text-center text-xs text-slate-500">This computer-generated invoice does not require a signature.</p></section>
}
