import { useQuery } from '@tanstack/react-query'
import { ArrowRight, BadgeCheck, Heart, LockKeyhole, Mail, Package, Settings, ShieldCheck, ShoppingBag, UserRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { getOrders } from '../api/orders'
import { useAuthStore } from '../stores/auth-store'
import { useCommerceStore } from '../stores/commerce-store'

// Owned by Member 4 (AI & Ops) — see TEAM.md
export function ProfilePage() {
  const user = useAuthStore((state) => state.user)
  const wishlist = useCommerceStore((state) => state.wishlist)
  const cart = useCommerceStore((state) => state.cart)
  const orders = useQuery({ queryKey: ['orders', 0, 1], queryFn: () => getOrders(0, 1) })
  const firstName = user?.fullName?.split(' ')[0] || 'there'
  const initials = user?.fullName?.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase() || 'NC'
  const role = user?.roles.includes('ROLE_SELLER') ? 'Seller account' : user?.roles.includes('ROLE_ADMIN') ? 'Administrator' : 'NovaCart member'
  const cartItems = Object.values(cart).reduce((sum, quantity) => sum + quantity, 0)

  return <main className="min-h-[75vh] bg-[var(--nc-bg)] px-5 py-10 text-[var(--nc-text)] sm:px-8 lg:py-14"><div className="mx-auto max-w-7xl">
    <section className="relative overflow-hidden rounded-[2.25rem] bg-slate-950 p-7 text-white shadow-float sm:p-10"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-violet-600/25 blur-3xl" /><div className="relative flex flex-col justify-between gap-8 md:flex-row md:items-end"><div className="flex items-center gap-5"><div className="grid h-20 w-20 shrink-0 place-items-center rounded-[1.6rem] bg-gradient-to-br from-violet-500 to-fuchsia-600 text-2xl font-black ring-4 ring-white/10">{initials}</div><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.16em] text-[#dfff36]"><BadgeCheck className="h-4 w-4" /> {role}</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em] sm:text-4xl">Welcome back, {firstName}</h1><p className="mt-2 text-sm text-slate-400">Manage your shopping activity and account from one place.</p></div></div><Link to="/settings" className="inline-flex h-11 items-center justify-center gap-2 rounded-full border border-white/15 bg-white/[.06] px-5 text-xs font-black hover:bg-white/10"><Settings className="h-4 w-4" /> Account settings</Link></div></section>
    <section className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-4">{[{ label: 'Orders', value: orders.data?.totalElements ?? '—', icon: Package, to: '/orders' }, { label: 'Wishlist', value: wishlist.length, icon: Heart, to: '/wishlist' }, { label: 'Cart items', value: cartItems, icon: ShoppingBag, to: '/cart' }, { label: 'Account', value: 'Verified', icon: ShieldCheck, to: '/settings' }].map((item) => <Link key={item.label} to={item.to} className="group rounded-[1.6rem] border border-black/10 bg-[var(--nc-surface)] p-5 transition hover:-translate-y-1 hover:shadow-card dark:border-white/10"><div className="flex justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 text-violet-700 dark:bg-[#dfff36]/10 dark:text-[#dfff36]"><item.icon className="h-5 w-5" /></span><ArrowRight className="h-4 w-4 text-slate-400 transition group-hover:translate-x-1" /></div><p className="mt-5 text-2xl font-black">{item.value}</p><p className="mt-1 text-xs font-bold text-slate-500">{item.label}</p></Link>)}</section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-[2rem] border border-black/10 bg-[var(--nc-surface)] p-6 dark:border-white/10 sm:p-8"><div className="flex items-center gap-3"><UserRound className="h-5 w-5 text-violet-600 dark:text-[#dfff36]" /><div><p className="nc-label">Personal information</p><h2 className="mt-1 text-xl font-black">Your NovaCart identity</h2></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><Info icon={UserRound} label="Full name" value={user?.fullName || 'Not provided'} /><Info icon={Mail} label="Email address" value={user?.email || 'Not provided'} /><Info icon={BadgeCheck} label="Account type" value={role} /><Info icon={ShieldCheck} label="Account status" value="Verified and active" /></div><p className="mt-6 rounded-2xl bg-black/[.035] p-4 text-xs leading-5 text-slate-500 dark:bg-white/[.04]">Delivery details remain securely attached to each order and are only used for fulfilment.</p></section><section className="rounded-[2rem] border border-black/10 bg-[var(--nc-surface)] p-6 dark:border-white/10 sm:p-8"><div className="flex items-center gap-3"><LockKeyhole className="h-5 w-5 text-violet-600 dark:text-[#dfff36]" /><div><p className="nc-label">Security</p><h2 className="mt-1 text-xl font-black">Account protection</h2></div></div><div className="mt-7 space-y-3"><SecurityRow title="Email verified" detail={user?.email || 'Account email'} active /><SecurityRow title="Secure session" detail="Your access refreshes automatically" active /><SecurityRow title="Password" detail="Reset it if you notice unusual activity" /></div><Link to="/forgot-password" className="mt-6 inline-flex items-center gap-2 text-xs font-black text-violet-700 hover:underline dark:text-[#dfff36]">Reset password <ArrowRight className="h-3.5 w-3.5" /></Link></section></div>
  </div></main>
}

function Info({ icon: Icon, label, value }: { icon: typeof UserRound; label: string; value: string }) { return <div className="rounded-2xl border border-black/[.07] p-4 dark:border-white/[.07]"><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-slate-500"><Icon className="h-3.5 w-3.5" /> {label}</p><p className="mt-2 truncate text-sm font-bold">{value}</p></div> }
function SecurityRow({ title, detail, active = false }: { title: string; detail: string; active?: boolean }) { return <div className="flex items-center gap-3 rounded-2xl border border-black/[.07] p-4 dark:border-white/[.07]"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${active ? 'bg-emerald-500 shadow-[0_0_12px_rgba(16,185,129,.55)]' : 'bg-slate-400'}`} /><div className="min-w-0"><p className="text-xs font-black">{title}</p><p className="mt-1 truncate text-[10px] text-slate-500">{detail}</p></div></div> }
