import { useMutation } from '@tanstack/react-query'
import { Bell, ChevronRight, LockKeyhole, LogOut, Mail, Moon, Palette, ShieldCheck, ShoppingBag, Sparkles, Sun, UserRound } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { logout } from '../api/auth'
import { useTheme } from '../hooks/useTheme'
import { useAuthStore } from '../stores/auth-store'

// Owned by Member 4 (AI & Ops) — see TEAM.md
export function SettingsPage() {
  const user = useAuthStore((state) => state.user)
  const clearAuth = useAuthStore((state) => state.clearAuth)
  const { theme, toggleTheme } = useTheme()
  const navigate = useNavigate()
  const [preferences, setPreferences] = useState(() => {
    try { return JSON.parse(localStorage.getItem('novacart-preferences') || '') as Record<string, boolean> } catch { return { orderUpdates: true, offers: true, aiTips: true } }
  })
  const signOut = useMutation({ mutationFn: logout, onSettled: () => { clearAuth(); navigate('/login', { replace: true }) } })
  const updatePreference = (key: string) => setPreferences((current) => { const next = { ...current, [key]: !current[key] }; localStorage.setItem('novacart-preferences', JSON.stringify(next)); return next })

  return <main className="min-h-[75vh] bg-[var(--nc-bg)] px-5 py-10 text-[var(--nc-text)] sm:px-8 lg:py-14"><div className="mx-auto max-w-6xl">
    <header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="nc-label">Your account</p><h1 className="mt-3 text-h2">Account settings</h1><p className="mt-3 text-sm text-slate-500">Control how NovaCart looks, communicates, and protects your account.</p></div><Link to="/profile" className="nc-secondary"><UserRound className="h-4 w-4" /> Back to profile</Link></header>
    <div className="mt-8 grid gap-6 lg:grid-cols-[240px_1fr]"><aside className="h-fit rounded-[1.75rem] bg-slate-950 p-5 text-white"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-500/20 font-black text-violet-200">{user?.fullName?.charAt(0).toUpperCase() || 'N'}</span><div className="min-w-0"><p className="truncate text-sm font-black">{user?.fullName}</p><p className="truncate text-[10px] text-slate-400">{user?.email}</p></div></div><div className="my-5 border-t border-white/10" /><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#dfff36]">Settings centre</p><p className="mt-3 text-xs leading-5 text-slate-400">Preferences are saved on this device and apply immediately.</p></aside>
    <div className="space-y-6"><Panel icon={Palette} eyebrow="Appearance" title="Choose your experience"><button onClick={toggleTheme} className="mt-6 flex w-full items-center justify-between rounded-2xl border border-black/10 p-4 text-left transition hover:border-violet-400 dark:border-white/10"><span className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-100 text-violet-700 dark:bg-[#dfff36]/10 dark:text-[#dfff36]">{theme === 'dark' ? <Moon className="h-5 w-5" /> : <Sun className="h-5 w-5" />}</span><span><span className="block text-sm font-black">{theme === 'dark' ? 'Dark mode' : 'Light mode'}</span><span className="mt-1 block text-xs text-slate-500">Tap to switch to {theme === 'dark' ? 'light' : 'dark'} mode</span></span></span><ChevronRight className="h-4 w-4 text-slate-400" /></button></Panel>
    <Panel icon={Bell} eyebrow="Notifications" title="What should we tell you about?"><div className="mt-5 divide-y divide-black/[.07] dark:divide-white/[.07]"><Toggle icon={ShoppingBag} title="Order updates" detail="Payment, shipping, delivery and cancellation alerts" checked={preferences.orderUpdates ?? true} onChange={() => updatePreference('orderUpdates')} /><Toggle icon={Mail} title="Offers and price drops" detail="Deals for products and categories you follow" checked={preferences.offers ?? true} onChange={() => updatePreference('offers')} /><Toggle icon={Sparkles} title="Nova AI suggestions" detail="Helpful shopping recommendations and reminders" checked={preferences.aiTips ?? true} onChange={() => updatePreference('aiTips')} /></div></Panel>
    <Panel icon={ShieldCheck} eyebrow="Security" title="Protect your account"><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link to="/forgot-password" className="group rounded-2xl border border-black/10 p-4 transition hover:border-violet-400 dark:border-white/10"><LockKeyhole className="h-5 w-5 text-violet-600 dark:text-[#dfff36]" /><p className="mt-4 text-sm font-black">Change password</p><p className="mt-1 text-xs leading-5 text-slate-500">Receive a secure password reset link.</p></Link><div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/[.05] p-4"><ShieldCheck className="h-5 w-5 text-emerald-500" /><p className="mt-4 text-sm font-black">Session protected</p><p className="mt-1 text-xs leading-5 text-slate-500">Secure automatic token refresh is active.</p></div></div><button onClick={() => signOut.mutate()} disabled={signOut.isPending} className="mt-5 inline-flex items-center gap-2 text-xs font-black text-rose-500 disabled:opacity-50"><LogOut className="h-4 w-4" /> {signOut.isPending ? 'Signing out…' : 'Sign out on this device'}</button></Panel></div></div>
  </div></main>
}

function Panel({ icon: Icon, eyebrow, title, children }: { icon: typeof Palette; eyebrow: string; title: string; children: React.ReactNode }) { return <section className="rounded-[2rem] border border-black/10 bg-[var(--nc-surface)] p-6 dark:border-white/10 sm:p-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 text-violet-700 dark:bg-[#dfff36]/10 dark:text-[#dfff36]"><Icon className="h-5 w-5" /></span><div><p className="nc-label">{eyebrow}</p><h2 className="mt-1 text-xl font-black">{title}</h2></div></div>{children}</section> }
function Toggle({ icon: Icon, title, detail, checked, onChange }: { icon: typeof Bell; title: string; detail: string; checked: boolean; onChange: () => void }) { return <div className="flex items-center justify-between gap-4 py-4 first:pt-0 last:pb-0"><span className="flex min-w-0 items-center gap-3"><Icon className="h-4 w-4 shrink-0 text-slate-400" /><span><span className="block text-sm font-black">{title}</span><span className="mt-1 block text-xs text-slate-500">{detail}</span></span></span><button type="button" role="switch" aria-checked={checked} onClick={onChange} className={`relative h-7 w-12 shrink-0 rounded-full transition ${checked ? 'bg-violet-600 dark:bg-[#dfff36]' : 'bg-slate-300 dark:bg-slate-700'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${checked ? 'left-6 dark:bg-slate-950' : 'left-1'}`} /></button></div> }
